;============================================================================
; CPU1Core1 Meter
;============================================================================

[CPU1Core1UsageString]
Meter=STRING
X=30
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 1"

[CPU1Core1PercentageString]
Meter=STRING
MeasureName=CPU1Core1
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core1UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core1UsageBar]
Meter=BAR
MeasureName=CPU1Core1
X=0r
Y=0r
W=160
H=7
BarColor=FF00FF
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core2 Meter
;============================================================================

[CPU1Core2UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 2"

[CPU1Core2PercentageString]
Meter=STRING
MeasureName=CPU1Core2
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core2UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core2UsageBar]
Meter=BAR
MeasureName=CPU1Core2
X=0r
Y=0r
W=160
H=7
BarColor=00FFFF
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core3 Meter
;============================================================================

[CPU1Core3UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 3"

[CPU1Core3PercentageString]
Meter=STRING
MeasureName=CPU1Core3
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core3UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core3UsageBar]
Meter=BAR
MeasureName=CPU1Core3
X=0r
Y=0r
W=160
H=7
BarColor=FFFF00
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core4 Meter
;============================================================================

[CPU1Core4UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 4"

[CPU1Core4PercentageString]
Meter=STRING
MeasureName=CPU1Core4
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core4UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core4UsageBar]
Meter=BAR
MeasureName=CPU1Core4
X=0r
Y=0r
W=160
H=7
BarColor=00FF00
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core5 Meter
;============================================================================

[CPU1Core5UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 5"

[CPU1Core5PercentageString]
Meter=STRING
MeasureName=CPU1Core5
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core5UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core5UsageBar]
Meter=BAR
MeasureName=CPU1Core5
X=0r
Y=0r
W=160
H=7
BarColor=FF5050
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core6 Meter
;============================================================================

[CPU1Core6UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 6"

[CPU1Core6PercentageString]
Meter=STRING
MeasureName=CPU1Core6
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core6UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core6UsageBar]
Meter=BAR
MeasureName=CPU1Core6
X=0r
Y=0r
W=160
H=7
BarColor=5050FF
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core7 Meter
;============================================================================

[CPU1Core7UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 7"

[CPU1Core7PercentageString]
Meter=STRING
MeasureName=CPU1Core7
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core7UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core7UsageBar]
Meter=BAR
MeasureName=CPU1Core7
X=0r
Y=0r
W=160
H=7
BarColor=FF00FF
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core8 Meter
;============================================================================

[CPU1Core8UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 8"

[CPU1Core8PercentageString]
Meter=STRING
MeasureName=CPU1Core8
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core8UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core8UsageBar]
Meter=BAR
MeasureName=CPU1Core8
X=0r
Y=0r
W=160
H=7
BarColor=00FFFF
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core9 Meter
;============================================================================

[CPU1Core9UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 9"

[CPU1Core9PercentageString]
Meter=STRING
MeasureName=CPU1Core9
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core9UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core9UsageBar]
Meter=BAR
MeasureName=CPU1Core9
X=0r
Y=0r
W=160
H=7
BarColor=FFFF00
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core10 Meter
;============================================================================

[CPU1Core10UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 10"

[CPU1Core10PercentageString]
Meter=STRING
MeasureName=CPU1Core10
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core10UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core10UsageBar]
Meter=BAR
MeasureName=CPU1Core10
X=0r
Y=0r
W=160
H=7
BarColor=00FF00
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core11 Meter
;============================================================================

[CPU1Core11UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 11"

[CPU1Core11PercentageString]
Meter=STRING
MeasureName=CPU1Core11
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core11UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core11UsageBar]
Meter=BAR
MeasureName=CPU1Core11
X=0r
Y=0r
W=160
H=7
BarColor=FF5050
BarOrientation=HORIZONTAL
AntiAlias=#AA#

;============================================================================
; CPU1Core12 Meter
;============================================================================

[CPU1Core12UsageString]
Meter=STRING
X=30
Y=10r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="Core 12"

[CPU1Core12PercentageString]
Meter=STRING
MeasureName=CPU1Core12
X=242
Y=0r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringEffect=Border
FontEffectColor=000000
AntiAlias=#AA#
Text="%1%"

[CPU1Core12UsageBarBack]
Meter=IMAGE
X=75
Y=3r
W=160
H=7
SolidColor=#colour7#
AntiAlias=#AA#
UpdateDivider=3600

[CPU1Core12UsageBar]
Meter=BAR
MeasureName=CPU1Core12
X=0r
Y=0r
W=160
H=7
BarColor=5050FF
BarOrientation=HORIZONTAL
AntiAlias=#AA#
