[variables]

;------------------------------------------------------------------
; Set your network interface number (0-5)
;------------------------------------------------------------------

Interface=0

;------------------------------------------------------------------
; Windows XP users should set this to 'TCP'
; Windows Vista or above users should set this to 'TCPv4'
;------------------------------------------------------------------

TCPVersion=TCPv4

;------------------------------------------------------------------
; Set maximum upload / download speed in bytes
;------------------------------------------------------------------

SpeedD=13000000
SpeedU=800000

;------------------------------------------------------------------
; Drive letters
;------------------------------------------------------------------

Drive1=C:
Drive2=D:
Drive3=E:
Drive4=F:
Drive5=G:
Drive6=H:
Drive7=I:
Drive8=J:
Drive9=K:
Drive10=L:
Drive11=M:
Drive12=N:
Drive13=O:
Drive14=P:
Drive15=Q:
Drive16=R:
Drive17=S:
Drive18=T:
Drive19=U:
Drive20=V:
Drive21=W:
Drive22=X:
Drive23=Y:
Drive24=Z:

;----------------------------------------------------
; Icons
;----------------------------------------------------

icon1=0, 187, 255, 220

;----------------------------------------------------
; Fonts
;----------------------------------------------------

; White
font1_name=Tahoma
font1_colour=255, 255, 255, 200

; Vertical Sidebar Text
font2_colour=255, 255, 255, 196

; Green
font3_colour=93, 255, 0, 196

; Orange
font4_colour=255, 157, 0, 220

; Red
font5_colour=255, 38, 0, 220

; Blue
font6_colour=0, 131, 255, 196

;----------------------------------------------------
; Anti-alias (Enable = 0 / Disable = 0)
;----------------------------------------------------

AA=0

;----------------------------------------------------
; Colour
;----------------------------------------------------

; Background
colour1=0, 0, 0, 200

; Sidebar
colour2=0, 0, 0, 255

; Sidebar Separator
colour3=0, 80, 187, 196

; Highlight
colour4=96, 96, 96, 96

; Shadow
colour5=0, 0, 0, 96

; Separator
colour6=0, 80, 187, 196

; Bar Background
colour7=100, 100, 100, 50

; Volume Bar Steps
colour8=196, 196, 196, 196

; Line / Bar (Green)
colour9=93, 255, 0, 196

; Line / Bar (Blue)
colour10=0, 160, 230, 196

; Line / Bar (Orange)
colour11=255, 157, 0, 220

; Line / Bar (Red)
colour12=255, 38, 0, 220

; Histogram (Blue)
colour13=0, 50, 100, 100

; Histogram (Green)
colour14=0, 200, 0, 100

; Line / Bar (White)
colour15=255, 255, 255, 220

; Histogram (White)
colour16=255, 255, 255, 100

; Histogram (Red)
colour17=255, 38, 0, 100
