;------------------------------------------------------------
; Headers
;------------------------------------------------------------

;------------------------------------------------------------
; GPU1 Headers
;------------------------------------------------------------
; GPU1 Name
;------------------------------------------------------------

[GPU1NameString]
Meter=STRING
MeasureName=MSIABGPU1Name
X=30
Y=5
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringStyle=Bold
AntiAlias=#AA#
UpdateDivider=3600
Text="GPU1 %1"

;------------------------------------------------------------
; GPU1 Clock Rate
;------------------------------------------------------------

[GPU1ClockRate]
Meter=STRING
MeasureName=MSIABGPU1CoreClock
X=0r
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
AntiAlias=#AA#
Text="Clock: %1 MHz"

;------------------------------------------------------------
; GPU1 Memory Clock Rate
;------------------------------------------------------------

[GPU1MemoryClockRate]
Meter=STRING
MeasureName=MSIABGPU1MemoryClock
X=0r
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
AntiAlias=#AA#
Text="Memory Clock: %1 MHz"

;------------------------------------------------------------
; GPU1 Memory Usage
;------------------------------------------------------------

[GPU1MemoryUsage]
Meter=STRING
MeasureName=MSIABGPU1MemoryUsage
X=0r
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
AntiAlias=#AA#
Text="Memory Usage: %1MB of #VIDEOMEM#MB"

;------------------------------------------------------------
; GPU2 Headers
;------------------------------------------------------------
; GPU2 Name
;------------------------------------------------------------

[GPU2NameString]
Meter=STRING
MeasureName=MSIABGPU2Name
X=30
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringStyle=Bold
AntiAlias=#AA#
UpdateDivider=3600
Text="GPU2 %1"

;------------------------------------------------------------
; GPU2 Clock Rate
;------------------------------------------------------------

[GPU2ClockRate]
Meter=STRING
MeasureName=MSIABGPU2CoreClock
X=0r
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
AntiAlias=#AA#
Text="Clock: %1 MHz"

;------------------------------------------------------------
; GPU2 Memory Clock Rate
;------------------------------------------------------------

[GPU2MemoryClockRate]
Meter=STRING
MeasureName=MSIABGPU2MemoryClock
X=0r
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
AntiAlias=#AA#
Text="Memory Clock: %1 MHz"

;------------------------------------------------------------
; GPU2 Memory Usage
;------------------------------------------------------------

[GPU2MemoryUsage]
Meter=STRING
MeasureName=MSIABGPU2MemoryUsage
X=0r
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
AntiAlias=#AA#
Text="Memory Usage: %1MB of #VIDEOMEM#MB"

;------------------------------------------------------------
; GPU3 Headers
;------------------------------------------------------------
; GPU3 Name
;------------------------------------------------------------

[GPU3NameString]
Meter=STRING
MeasureName=MSIABGPU3Name
X=30
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
StringStyle=Bold
AntiAlias=#AA#
UpdateDivider=3600
Text="GPU3 %1"

;------------------------------------------------------------
; GPU3 Clock Rate
;------------------------------------------------------------

[GPU3ClockRate]
Meter=STRING
MeasureName=MSIABGPU3CoreClock
X=0r
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
AntiAlias=#AA#
Text="Clock: %1 MHz"

;------------------------------------------------------------
; GPU3 Memory Clock Rate
;------------------------------------------------------------

[GPU3MemoryClockRate]
Meter=STRING
MeasureName=MSIABGPU3MemoryClock
X=0r
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
AntiAlias=#AA#
Text="Memory Clock: %1 MHz"

;------------------------------------------------------------
; GPU3 Memory Usage
;------------------------------------------------------------

[GPU3MemoryUsage]
Meter=STRING
MeasureName=MSIABGPU3MemoryUsage
X=0r
Y=15r
FontColor=#font1_colour#
FontSize=8
FontFace=#font1_name#
AntiAlias=#AA#
Text="Memory Usage: %1MB of #VIDEOMEM#MB"
