[CPU1Core1]
Measure=Plugin
Plugin=Plugins\CoreTemp.dll
CoreTempType=Load
CoreTempIndex=0
MinValue=0
MAxValue=100

[CPU1Core1Temp]
Measure=Plugin
PlugIn=PlugIns\CoreTemp.dll
CoreTempType=Temperature
CoreTempIndex=0
MaxValue=100
MinValue=0

[CPU1Core2]
Measure=Plugin
Plugin=Plugins\CoreTemp.dll
CoreTempType=Load
CoreTempIndex=1
MinValue=0
MAxValue=100

[CPU1Core2Temp]
Measure=Plugin
PlugIn=PlugIns\CoreTemp.dll
CoreTempType=Temperature
CoreTempIndex=1
MaxValue=100
MinValue=0

[CPU1Core3]
Measure=Plugin
Plugin=Plugins\CoreTemp.dll
CoreTempType=Load
CoreTempIndex=2
MinValue=0
MAxValue=100

[CPU1Core3Temp]
Measure=Plugin
PlugIn=PlugIns\CoreTemp.dll
CoreTempType=Temperature
CoreTempIndex=2
MaxValue=100
MinValue=0

[CPU1Core4]
Measure=Plugin
Plugin=Plugins\CoreTemp.dll
CoreTempType=Load
CoreTempIndex=3
MinValue=0
MAxValue=100

[CPU1Core4Temp]
Measure=Plugin
PlugIn=PlugIns\CoreTemp.dll
CoreTempType=Temperature
CoreTempIndex=3
MaxValue=100
MinValue=0

[CPU1Core5]
Measure=Plugin
Plugin=Plugins\CoreTemp.dll
CoreTempType=Load
CoreTempIndex=4
MinValue=0
MAxValue=100

[CPU1Core5Temp]
Measure=Plugin
PlugIn=PlugIns\CoreTemp.dll
CoreTempType=Temperature
CoreTempIndex=4
MaxValue=100
MinValue=0

[CPU1Core6]
Measure=Plugin
Plugin=Plugins\CoreTemp.dll
CoreTempType=Load
CoreTempIndex=5
MinValue=0
MAxValue=100

[CPU1Core6Temp]
Measure=Plugin
PlugIn=PlugIns\CoreTemp.dll
CoreTempType=Temperature
CoreTempIndex=5
MaxValue=100
MinValue=0

[CPU1Core7]
Measure=Plugin
Plugin=Plugins\CoreTemp.dll
CoreTempType=Load
CoreTempIndex=6
MinValue=0
MAxValue=100

[CPU1Core7Temp]
Measure=Plugin
PlugIn=PlugIns\CoreTemp.dll
CoreTempType=Temperature
CoreTempIndex=6
MaxValue=100
MinValue=0

[CPU1Core8]
Measure=Plugin
Plugin=Plugins\CoreTemp.dll
CoreTempType=Load
CoreTempIndex=7
MinValue=0
MAxValue=100

[CPU1Core8Temp]
Measure=Plugin
PlugIn=PlugIns\CoreTemp.dll
CoreTempType=Temperature
CoreTempIndex=7
MaxValue=100
MinValue=0

[CPU1Core9]
Measure=Plugin
Plugin=Plugins\CoreTemp.dll
CoreTempType=Load
CoreTempIndex=8
MinValue=0
MAxValue=100

[CPU1Core9Temp]
Measure=Plugin
PlugIn=PlugIns\CoreTemp.dll
CoreTempType=Temperature
CoreTempIndex=8
MaxValue=100
MinValue=0

[CPU1Core10]
Measure=String
String=0

[CPU1Core10Temp]
Measure=String
String=0

[CPU1Core11]
Measure=String
String=0

[CPU1Core11Temp]
Measure=String
String=0

[CPU1Core12]
Measure=String
String=0

[CPU1Core12Temp]
Measure=String
String=0

